# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
# Database info
DB_MYSQL_HOST: 0.tcp.ngrok.io
DB_MYSQL_PORT: 18707
DB_MYSQL_USER: root
DB_MYSQL_DATABASE: rubytraining_development
DB_MYSQL_PASSWORD: 1234

# Mailer info
MAILER_USER: tumv.mailer@gmail.com
MAILER_PASSWORD: tumvmailer
MAILER_DOMAIN: tumv.info
MAILER_PORT: 587
MAILER_ADDRESS: smtp.gmail.com
